### ISSUE TITLE
Upgrading to macOs Sierra breaks the tool

### ISSUE THREAD

**Issue by denisfrietman** [RickGroenewegen/sublime-sync#2]
<img width="1064" alt="schermafbeelding 2016-09-21 om 14 19 25" src="https://cloud.githubusercontent.com/assets/6150987/18710615/6b2bc350-8006-11e6-9db5-a64d3543769e.png">

It generates the above error messages in an infinite loop.

**Comment by michaelmaat** [comment]
Fix SSH and SFTP on macOS Sierra: http://blog.chlaird.com/2016/06/macos-1012-sierra-corrupted-mac-on.html

**Comment by RickGroenewegen** [comment]
Should be fixed now
