### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by herrschuessler** [RickGroenewegen/sublime-sync#4]
Hi @RickGroenewegen,

this script is exactly what I've been looking for for ages. But with most of the remote servers that I tried to connect to, I get errors or unexpected behaviour, often resulting in `Nonzero exit code: 255`.

Is there any way to find out what's the real problem, i.e. getting more details on errors and connection aborts with this script?

**Comment by RickGroenewegen** [comment]
Hi Cristoph,

Are you trying to connect using a username and password? Or with a SSH key?

Rick

**Comment by herrschuessler** [comment]
Hi Rick,

I'm trying to connect by usernamen and password.

**Comment by RickGroenewegen** [comment]
Which OS are you using? Can you try removing the server from your 'known_hosts' file and try connecting manually using the 'ssh' command to the server and accept the prompt that asks if the host should be added to the known hosts?

**Comment by herrschuessler** [comment]
I'm on MacOS and since I'm connecting via FTP, not SFTP or SSH, the server isn't in the `known_hosts`.

**Comment by RickGroenewegen** [comment]
I'm afraid it currently only supports SFTP :(
